### ISSUE TITLE
Remote configuration files should be configurable with sensible defaults

### ISSUE THREAD

**Issue by eriknelson** [fusor/cpma#132]
Spawned from PR https://github.com/fusor/cpma/pull/128#discussion_r283117690

Remote config file path consts should be provided by cli/cpma-configfile values, with sensible defaults. I think this is something we should be able to handle with viper.

**Comment by jmontleon** [comment]
We should be able to do this with spf13/viper, which is being used in the env package.

https://github.com/spf13/viper#establishing-defaults

With viper we also shouldn't need to pass Config around, since we can get the values from it when we need to.

Ideally I'd like to:
- Move env under pkg
- Set Defaults with viper
- Maybe rework a little where we look for cpma.yml.
 - I was thinking along the lines of:
  - whatever is passed into --config
  - $pwd/cpma.yml (this is the new one)
  - $home/cpma.yml
- Stop passing the Config struct around and use the env package / viper to get values when need.

**Comment by eriknelson** [comment]
@jmontleon #142 partially addresses this, but I think we probably want to get this in before really considering this fixed:

> Stop passing the Config struct around and use the env package / viper to get values when need.

What do you think?

**Comment by eriknelson** [comment]
The issues I hit while running the tool around this have been resolved by relying on viper thanks to @jmontleon, I'm going to close this. Feel free to re-open if we think this deserves more conversation.
