### ISSUE TITLE
OAuth transform for Basic Auth has placeholder data and is incomplete.

### ISSUE THREAD

**Issue by jwmatthews** [fusor/cpma#149]
Basic Auth support needs to be re-examined, I imagine this hasn't been tested against a real cluster yet.

https://github.com/fusor/cpma/blob/master/pkg/transform/oauth/basicauth.go#L45-L55
```golang
	// TODO: Fetch cert and key
	certFile := "456This is pretend content"
	encoded := base64.StdEncoding.EncodeToString([]byte(certFile))
	certSecret := secrets.GenSecret(certSecretName, encoded, "openshift-config", "basicauth")

	keySecretName := p.Name + "-client-key-secret"
	idP.BasicAuth.TLSClientKey.Name = keySecretName

	keyFile := "123This is pretend content"
	encoded = base64.StdEncoding.EncodeToString([]byte(keyFile))
	keySecret := secrets.GenSecret(keySecretName, encoded, "openshift-config", "basicauth")

```

**Comment by jwmatthews** [comment]
@alexander-demichev let's target this issue for next sprint.   I'll ensure we add it to Sprint 6 planning.

**Comment by jmontleon** [comment]
There are several providers with placeholder data that need some attention, not just basic auth.

**Comment by jmontleon** [comment]
I think, how that we have extract set up we need to start looking for and Fetching CA's, Client Cert's, Client Key's, Secrets, etc. and start populating their content in the IdentityProvider struct. I think I extended the IndentityProvider for those 3. 

I think Secrets are getting grabbed and populated already, but noticed some secrets are being base64 encoded:
https://github.com/fusor/cpma/blob/master/pkg/transform/oauth/github.go#L48-L49

Others are not:
https://github.com/fusor/cpma/blob/master/pkg/transform/oauth/google.go#L37

I'm not sure if this intentional or they all should be base64 encoded?

**Comment by alexander-demichev** [comment]
I think all secrets should be base63, will test it soon

**Comment by jmontleon** [comment]
Example for getting and loading ca's, certs, and keys

**Comment by alexander-demichev** [comment]
@jwmatthews  I think @jmontleon  fixed it, can we close the issue?
