### ISSUE TITLE
CI implementation

### ISSUE THREAD

**Issue by jmontleon** [fusor/cpma#252]
Leverage the work being done for the controller and implement end to end tests to 
- bring up both an OCP3 and 4 cluster
- generate a report
- apply transforms

**Comment by Danil-Grigorev** [comment]
The workflow described in the issue is introduced in https://github.com/fusor/mig-ci/pull/68 and will be executed every time a change is detected in `master` branch. Main target is to test applying transforms on OCP4 cluster, which works for source clusters for all supported versions (3.7-3.11).

The report testing is based on https://github.com/fusor/cpma/pull/285 and in order to be complete, needs to update with changes described in https://github.com/fusor/cpma/issues/300 . The initial implementation worked for version 3.11, reports were sane. Most of the report generation workflow is tested with mocked API by PRs https://github.com/fusor/cpma/pull/292 and following ones.
