### ISSUE TITLE
Deeper integreation with api in cluster report.

### ISSUE THREAD

**Issue by Danil-Grigorev** [fusor/cpma#280]
Current implementation of namespace cluster report relies on a custom structure defined as map. https://github.com/fusor/cpma/blob/7faab196ad81b8a5ddd895a3b0d4262df6eb8152/pkg/api/requests.go#L13-L16

It might make sense to use `NamespaceList` from API. This will simplify operations on the resources, and will prevent problems with unsorted nature of a `map` data type.

**Comment by gildub** [comment]
I might have missed something but it seems to me that `NamespaceList` is not going to cut it here because the NamespaceResources contains a list of objects belonging to each namespace.
I haven't found a place holder in k8s that does the job and one of the reason is that namespace is k8s and o7t has projects, by practice it's kind of 1:1 relationship, meanwhile we need to hold all the objects belonging to each namespace/project that are k8s and o7t with routes, quotes, etc for the latter.

**Comment by Danil-Grigorev** [comment]
I agree. But in general the `requests.go` package contain API requests, and the structure there saves response. Lines https://github.com/fusor/cpma/blob/7faab196ad81b8a5ddd895a3b0d4262df6eb8152/pkg/api/requests.go#L19-L23 could be substituted with a structure, which will have the namespace name too, and this will serve the same purpose as a map, avoiding it's issues. The speed up of iteration with `range` will be in place too.
